# Generated by Django 2.1.4 on 2018-12-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('categorieName', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
    ]
